### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-Maquetacion-web-con-HTML5-y-CSS3_ed6#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos *issues* nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by jmreycanay** [comment]
## Hola !!!

Mi nombre es José Manuel 

Hace más de 20 años que acabé mis estudios de [Ingeniería Técnica de Informática](https://www.etsisi.upm.es/estudios/tecnicos) y siempre estado en la parte del Backend aunque nunca como desarrollador.

Así que me he tomado un "descanso" para reciclarme todo lo posible, y el FullStack en Javascript me parece muy interesante, por lo que HTML5 y CCS3 me parece una forma estupenda de empezar de "arriba hacia abajo" :+1: 

Saludos !!!

**Comment by blancarogel** [comment]
**Hola!**
Soy Blanca, soy licenciada en periodismo por la http://www.ucm.es pero he trabajado como ~~periodista~~  diseñadora en temas de infografía y diseño, casi siempre para temas offline. Actualmente trabajo en el departamento de diseño de Securitas Direct y me dedido a temas offline puro y duro. Me he apuntado a este curso para ampliar posibilidades y poder trabajar como *front* (o lo que me pidan). A día de hoy, mi nivel de código es casi cero; ni siquiera manejo Wordpress así que espero que tengáis paciencia conmigo!

Tengo que decir que Github me parece horrible y poco intuitivo, pero seguiré las indicaciones del grandmaster @UlisesGascon para llegar a entender todo esto del mundo web. De momento estoy haciendo pruebas con Markdown, que parece ser una especie de lenguaje propio de Github, no? Ulises, sé que te parecerá absurdo pero no sé cómo crear mi carpeta privada en el repositorio. Y por lo de un archivo *Hello world*, ¿te refieres a un documento de texto con markdown, como esto que estoy haciendo ahora?

Un saludo a todos! Disfrutad las vacaciones

**Comment by UlisesGascon** [comment]
Hola a todos! 

He creado un nuevo *[issue](https://github.com/Fictizia/Curso-Maquetacion-web-con-HTML5-y-CSS3_ed6/issues/2)* que espero pueda ayudaros a dar fácilmente los primeros pasos con GitHub. 

@jmreycanay: Me alegro de ver que te gustan los retos! FullStack es el camino en el que más se aprende. HTML5 y CSS3 es un muy buen primer paso :+1: 

@blancarogel Es cierto que GitHub es poco intuitivo y la versión web necesita muchas mejoras en cuanto a usabilidad, pero comparado con GIT por consola es un mundo de ciencia ficción :joy:

[Markdown](http://whatismarkdown.com/) cada día se hace más popular, muchas aplicaciones ya cuentan con soporte como Trello, WordPress (vía plugins), etc...

El nivel de código no es un problema! La idea es empezar desde cero y crear unos cimientos sólidos :wink:

Disfrutad las vacaciones, nos vemos el martes (29/03)!
