### ISSUE TITLE
Animación de Broadway Boogie-Woogie

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-Maquetacion-web-con-HTML5-y-CSS3_ed6#10]
Hola @manuelarenas !

Ya tengo la [animación lista](http://codepen.io/ulisesgascon/pen/e254798dc87070858413b984c0151104) :)

En clase os explico en detalle la parte de JavaScript línea a línea... pero básicamente lo que hace es buscar aquellos elementos en el html que sean de la clase *color_red*, *color_blue* o *color_white* y les asigna cada X segundos un [animation-timing-function](http://www.w3schools.com/cssref/css3_pr_animation-timing-function.asp) diferente.

Yo he usado solamente *ease*, *ease-out*, *ease-in* y *ease-in-out*... pero perfectamente podríamos usar muchas más... incluso podrías crear algunos patrones personalizados usando *cubic-bezier* desde [este generador](http://cubic-bezier.com/) y mañana los incorporamos al diseño.

He modificado un par de puntos el CSS, pero te he dejado comentarios. Básicamente he usando la propiedad *overflow: hidden* para hacer desaparecer los cuadrados que se salen de pista, tanto en algunas pistas como en el marco *main_bbb*. También he añadido más recorrido vertical en la animación y ahora todos los colores llegan hasta abajo  ;-)

Un abrazo!

**Comment by manuelarenas** [comment]
Genial! Gracias le echo un ojo!
