### ISSUE TITLE
Localización y restaurante

### ISSUE THREAD

**Issue by blancarogel** [Fictizia/Curso-Maquetacion-web-con-HTML5-y-CSS3_ed6#4]
Acabo de subir el ejercicio del restaurante y me han entrado dos dudas @UlisesGascon :
1) ¿Deberíamos hacerlo con .css asociada? Porque entiendo que algunos de mis compis ya maquetan con html y css, pero yo no controlo estos lenguajes y no sé muy bien cómo hacer lo del .css.
2) Me estoy volviendo loca para meter el mapa en la sección de 'contacto' y no lo encuentro! ¿Cuál era la etiqueta necesaria para poner algo tipo localización de Google Maps?
Gracias! Mañana nos vemos!

**Comment by UlisesGascon** [comment]
Hola @blancarogel.

He mirado lo que has subido y esta genial. Para trabajar con los mapas es necesario usar la etiqueta *&lt;iframe&gt;*, muchos sitios como Youtube o Google maps ofrecen entre las opciones de compartir la de "insertar en web". Normalmente ellos ya nos facilitan este código. 

```html
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3037.40170663965!2d-3.720401048893044!3d40.422103063134955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd42288624178bff%3A0xaceb2ce3f952eea!2sFictizia!5e0!3m2!1ses!2ses!4v1460443770809" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
```

Hoy veremos en clase todo lo relacionado a insertar contenidos de terceros (Google Maps y Youtube). En cuanto a *.css*, en la clase de hoy empezaremos a crear y trabajar con nuestras propias hojas de estilo. En el caso del ejercicio de las tablas. Os había preparado un poco de css para que los navegadores os pintaran los bordes de las celdas y la tabla. 

Solo sería necesario copiar el css en un archivo con extensión *.css* e incluirlo en nuestro html usando la etiqueta *&lt;link&gt;*. Hoy será el día que empecemos a trabajar ya estructuradamente con las hojas de estilo y empezaremos desde cero, como hicimos antes con el HTML ;-)

Nos vemos esta tarde!
