### ISSUE TITLE
Seminario en streaming

### ISSUE THREAD

**Issue by blancarogel** [Fictizia/Curso-Maquetacion-web-con-HTML5-y-CSS3_ed6#5]
Pero bueno!! Ulises, he pillado el seminario en el momento de los 'textiles inteligentes' y entre eso y el tema de la acuaponia me he quedado loca! Ya nos contarás más cosas del huerto inteligente, que me parece muy interesante. Un saludo!

**Comment by UlisesGascon** [comment]
Hahaha! Gracias!  El próximo martes nos ponemos al día :-D 

Ha sido muy divertido 

Un abrazo!

**Comment by UlisesGascon** [comment]
Hola a todos!

Os paso [el link](http://www.blog.ulisesgascon.com/seminario-de-internet-of-things-en-huelva-inteligente/) para que podáis ver el todo el seminario en youtube. 

Como curiosidad.... el [sistema de presentación](http://lab.hakim.se/reveal-js/#/) que utilicé se monta usando HTML, CSS y JavaScript. 

Nos vemos el jueves!
