### ISSUE TITLE
Duda fotos ampliadas

### ISSUE THREAD

**Issue by blancarogel** [Fictizia/Curso-Maquetacion-web-con-HTML5-y-CSS3_ed6#6]
@UlisesGascon , ¿existe alguna etiqueta para ampliar las fotos? Igul a través de .css o así... ¿Como el <allowfullscreen> para vídeo?

**Comment by UlisesGascon** [comment]
Hola @blancarogel,

Se pueden usar los atributos *width* y *height* para determinar el valor en píxeles de las fotos desde la propia etiqueta, hoy en clase veremos como trabajarlo directamente desde las hojas de estilo... que es la manera más optima :+1:
