### ISSUE TITLE
Bauhaus

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-Maquetacion-web-con-HTML5-y-CSS3_ed6#8]
hola!

Te paso el link al [demo de Bauhaus](http://codepen.io/ulisesgascon/pen/vGvzyp)

Un abrazo!

**Comment by UlisesGascon** [comment]
Hola de nuevo! 

He mejorado un poco el diseño anterior. Siguiendo esta vez como referencia esta portada

![portada](https://cdn.taschen.com/media/images/960/25_bauhaus_ad_gb_3d_01564_1503121813_id_909166.png)

- **[Nuevo diseño](http://codepen.io/ulisesgascon/pen/vGvzyp)**

**Comment by blancarogel** [comment]
Genial, muchas gracias @UlisesGascon ! Voy a estudiar un poco el código, a ver si lo pillo :-)
