### ISSUE TITLE
Web molona con fondo de colores

### ISSUE THREAD

**Issue by blancarogel** [Fictizia/Curso-Maquetacion-web-con-HTML5-y-CSS3_ed6#9]
http://www.albertomoro.it/
@UlisesGascon es esto!

**Comment by UlisesGascon** [comment]
[Aquí esta](http://codepen.io/ulisesgascon/pen/f9e1dc654cad3afda80bb5bab5870e6b/) reducido y sintetizado el efecto que se usa
